[package]
name = "uefi_loader"
version = "0.1.0"
authors = ["orumin <dev@orum.in>"]

[lib]
path = "loader.rs"
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0"
uefi  = "0.1.2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
